name: taskati
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  image_picker: ^1.1.2
  gap: ^3.0.1
  intl: any
  date_picker_timeline: ^1.2.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter:


  uses-material-design: true


  assets:
    - asset/image/
    - asset/font/
    - asset/lottie/

  fonts:
    - family: poppins
      fonts:
        - asset: asset/font/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: asset/font/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: asset/font/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: asset/font/poppins/Poppins-Bold.ttf
          weight: 700
